# Generated by Django 6.0.2 on 2026-02-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomName", models.CharField(max_length=20, unique=True)),
                ("capacity", models.IntegerField()),
                ("hasProjector", models.BooleanField(default=False)),
                ("hasComputers", models.BooleanField(default=False)),
                ("blockLocation", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("bookingID", models.AutoField(primary_key=True, serialize=False)),
                ("bookingDate", models.DateField()),
                ("periodNumber", models.IntegerField()),
                ("subject", models.CharField(max_length=50)),
                ("classSize", models.IntegerField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookings.room"
                    ),
                ),
            ],
        ),
    ]
