# Generated by Django 6.0.2 on 2026-02-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="subject",
            new_name="className",
        ),
    ]
