# Generated by Django 6.0.3 on 2026-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_status_booking_transferto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("pending", "Pending Transfer"),
                    ("rejected", "Transfer Rejected"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
